version: "3.8"

services:
  leetcode_bot:
    container_name: ${CONTAINER_NAME}
    restart: always
    build:
      context: .
      dockerfile: ./deployment/Dockerfile
    image: leetcode_bot
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm start
    networks:
      - database_network

networks:
  database_network:
    name: ${DATABASE_NETWORK}
    external: true
