version: '3'

services:
  leetcode_bot:
    container_name: ${CONTAINER_NAME}
    restart: always
    build:
      context: .
      dockerfile: ./deployment/Dockerfile
    image: leetcode_bot
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm start
    networks:
      - database_network

networks:
  database_network:
    external:
      name: ${DATABASE_NETWORK}
